name: maksim2042
favicon: null
layout_spectrum: 0.05262338020838797
typography_spectrum: 0.6255520230624825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6773238710593432
  lightness: 0.8864134980831295
  saturation: 0.3452696749009192
  rhythmicContrast: 0.19446555757895112
purpose: []
